Modyfikacje = {
    -- światła
    ['22'] = {
		{name = "Fabryczne Światła", mod = 0, price = 0.4 * 0},
		{name = "Białe Światła", mod = 1, price = 0.4 * 1625},
		{name = "Granatowe Światła", mod = 3, price = 0.4 * 2625},
		{name = "Niebieskie Światła", mod = 4, price = 0.4 * 2625},
		{name = "Turkusowe Światła", mod = 5, price = 0.4 * 2625},
		{name = "Limonkowe Światła", mod = 6, price = 0.4 * 2625},
		{name = "Żółte Światła", mod = 7, price = 0.4 * 2625},
		{name = "Jasno Pomarańczowe Światła", mod = 8, price = 0.4 * 2625},
		{name = "Pomarańczowe Światła", mod = 9, price = 0.4 * 2625},
		{name = "Czerwone Światła", mod = 10, price = 0.4 * 2625},
		{name = "Łososiowe Światła", mod = 11, price = 0.4 * 2625},
		{name = "Różowe Światła", mod = 12, price = 0.4 * 2625},
		{name = "Fioletowe Światła", mod = 13, price = 0.4 * 2625},
		{name = "Jasno Fioletowe Światła", mod = 14, price = 0.4 * 2625},
    },
    -- turbina
    ['18'] = {
		{ name = "Brak", mod = 0, price = 0},
		{ name = "Turbosprężarka", mod = 1, price = 15000},
    },
    -- zawieszenie
    ['15'] = {
		{name = "Fabryczne Zawieszenie",mod = -1, price = 400},
		{name = "Obniżone Zawieszenie",mod = 0, price = 600},
		{name = "Uliczne Zawieszenie",mod = 1, price = 900},
		{name = "Sportowe Zawieszenie",mod = 2, price = 1300},
		{name = "Torowe Zawieszenie",mod = 3, price = 1500},
    },
    -- klakson
    ['14'] = {
		{name = "Fabryczny", mod = -1, price = 0.4 * 1625},
		{name = "Ciężarówka", mod = 0, price = 0.4 * 1625},
		{name = "Policyjny", mod = 1, price = 0.4 * 4062},
		{name = "Błazen", mod = 2, price = 0.4 * 6500},
		{name = "Muzyczny 1", mod = 3, price = 0.4 * 11375},
		{name = "Muzyczny 2", mod = 4, price = 0.4 * 11375},
		{name = "Muzyczny 3", mod = 5, price = 0.4 * 11375},
		{name = "Muzyczny 4", mod = 6, price = 0.4 * 11375},
		{name = "Muzyczny 5", mod = 7, price = 0.4 * 11375},
		{name = "Smutny Puzon", mod = 8, price = 0.4 * 11375},
		{name = "Klasyczny 1", mod = 9, price = 0.4 * 11375},
		{name = "Klasyczny 2", mod = 10, price = 0.4 * 11375},
		{name = "Klasyczny 3", mod = 11, price = 0.4 * 11375},
		{name = "Klasyczny 4", mod = 12, price = 0.4 * 11375},
		{name = "Klasyczny 5", mod = 13, price = 0.4 * 11375},
		{name = "Klasyczny 6", mod = 14, price = 0.4 * 11375},
		{name = "Klasyczny 7", mod = 15, price = 0.4 * 11375},
		{name = "Scaledo", mod = 16, price = 0.4 * 11375},
		{name = "Scalere", mod = 17, price = 0.4 * 11375},
		{name = "Scalemi", mod = 18, price = 0.4 * 11375},
		{name = "Scalefa", mod = 19, price = 0.4 * 11375},
		{name = "Scalesol", mod = 20, price = 0.4 * 11375},
		{name = "Scalela", mod = 21, price = 0.4 * 11375},
		{name = "Scaleti", mod = 22, price = 0.4 * 11375},
		{name = "Scaledo High", mod = 23, price = 0.4 * 11375},
		{name = "Jazzowy 1", mod = 25, price = 0.4 * 11375},
		{name = "Jazzowy 2", mod = 26, price = 0.4 * 11375},
		{name = "Jazzowy 3", mod = 27, price = 0.4 * 11375},
		{name = "Jazzowy Pętla", mod = 28, price = 0.4 * 11375},
		{name = "Starspangban 1", mod = 29, price = 0.4 * 11375},
		{name = "Starspangban 2", mod = 30, price = 0.4 * 11375},
		{name = "Starspangban 3", mod = 31, price = 0.4 * 11375},
		{name = "Starspangban 4", mod = 32, price = 0.4 * 11375},
		{name = "Classicalloop 1", mod = 33, price = 0.4 * 11375},
		{name = "Classicalloop 2", mod = 34, price = 0.4 * 11375},
		{name = "Classicalloop 3", mod = 35, price = 0.4 * 11375},
    },
    -- skrzynia
    ['13'] = {
		{name = "Fabryczna Skrzynia Biegów", mod = -1, price = 1000},
		{name = "Uliczna Skrzynia Biegów", mod = 0, price = 7000},
		{name = "Sportowa Skrzynia Biegów", mod = 1, price = 10000},
		{name = "Torowa Skrzynia Biegów", mod = 2, price = 15000},
    },
    -- hamulce
    ['12'] = {
		{name = "Fabryczne Hamulce", mod = -1, price = 1000},
		{name = "Uliczne Hamulce", mod = 0, price = 8000},
		{name = "Sportowe Hamulce", mod = 1, price = 13000},
		{name = "Torowe Hamulce", mod = 2, price = 17500},
    },
    -- silnik
    ['11'] = {
		{name = "Fabryczny", mod = -1, price = 1000},
		{name = "Pakiet Podstawowy", mod = 0, price = 13000},
		{name = "Pakiet Uliczny", mod = 1, price = 15500},
		{name = "Pakiet Sportowy", mod = 2, price = 19000},
		{name = "Pakiet Torowy", mod = 3, price = 25000},
    },
    -- szyby
    ['46'] = {
        { name = "Fabryczne", mod = -1, price = 0.4 * 1000},
		{ name = "Czysta Czerń", mod = 1, price = 0.4 * 1000},
		{ name = "Ciemny Dym", mod = 2, price = 0.4 * 1000},
		{ name = "Lekki Dym", mod = 3, price = 0.4 * 1000},
		{ name = "Limuzynowe", mod = 4, price = 0.4 * 1000},
		{ name = "Zieleń", mod = 5, price = 0.4 * 1000},
    },
    ['tires'] = {
        { name = "Biały Dym",smokecolor = {254,254,254}, price = 0.4 * 3000},
        { name = "Czarny Dym", smokecolor = {1,1,1}, price = 0.4 * 3000},
        { name = "Niebieski Dym", smokecolor = {0,150,255}, price = 0.4 * 3000},
        { name = "Zółty Dym", smokecolor = {255,255,50}, price = 0.4 * 3000},
        { name = "Pomarańczowy Dym", smokecolor = {255,153,51}, price = 0.4 * 3000},
        { name = "Czerwony Dym", smokecolor = {255,10,10}, price = 0.4 * 3000},
        { name = "Zielony Dym", smokecolor = {10,255,10}, price = 0.4 * 3000},
        { name = "Fioletowy Dym", smokecolor = {153,10,153}, price = 0.4 * 3000},
        { name = "Różowy Dym", smokecolor = {255,102,178}, price = 0.4 * 3000},
        { name = "Szary Dym",smokecolor = {128,128,128}, price = 0.4 * 3000},
    },
    ['tablice'] = {
		{ name = "SA EXEMPT", plateindex = 4, price = 0.4 * 200},
		{ name = "San Andreas", plateindex = 0, price = 0.4 * 200},
		{ name = "San Andreas 2", plateindex = 3, price = 0.4 * 200},
		{ name = "San Andreas 3", plateindex = 2, price = 0.4 * 300},
		{ name = "San Andreas 4", plateindex = 1, price = 0.4 * 600},
    },
    ['neon'] = {
		{name = "Brak", neons = {false, false, false, false}, price = 0.4 * 5000},
		{name = "Przód i Tył", neons = {false, false, true, true}, price = 0.4 * 5000},
		{name = "Boki", neons = {true, true, false, false}, price = 0.4 * 5000},
		{name = "Przód, Tył i Boki", neons = {true, true, true, true}, price = 0.4 * 5000},
    },
    ['neonColor'] = {
		{ name = "Biel", neon = {255,255,255}, price = 0.4 * 1000},
		{ name = "Błękit", neon = {0,0,255}, price = 0.4 * 1000},
		{ name = "Elektryczny Błękit", neon = {0,150,255}, price = 0.4 * 1000},
		{ name = "Miętowa Zieleń", neon = {50,255,155}, price = 0.4 * 1000},
		{ name = "Limonkowa Zieleń", neon = {0,255,0}, price = 0.4 * 1000},
		{ name = "Zółć", neon = {255,255,0}, price = 0.4 * 1000},
		{ name = "Złoty", neon = {204,204,0}, price = 0.4 * 1000},
		{ name = "Pomarańcz", neon = {255,128,0}, price = 0.4 * 1000},
		{ name = "Czerwień", neon = {255,0,0}, price = 0.4 * 1000},
		{ name = "Kucykowy Róż", neon = {255,102,255}, price = 0.4 * 1000},
		{ name = "Gorący Róż",neon = {255,0,255}, price = 0.4 * 1000},
		{ name = "Fiolet", neon = {153,0,153}, price = 0.4 * 1000},
		{ name = "Brąz", neon = {139,69,19}, price = 0.4 * 1000},
    },
    ['colors'] = {
        {name = "nil", colorindex = 0},{name = "nil2", colorindex = 0},
        {name = "Czerń", colorindex = 0},{name = "Karbonowa Czerń", colorindex = 147},
        {name = "Grafitowy", colorindex = 1},{name = "Antracytowa Czerń", colorindex = 11},
        {name = "Czarna Stal", colorindex = 2},{name = "Ciemna Stal", colorindex = 3},
        {name = "Srebrowy", colorindex = 4},{name = "Niebieskawe Srebro", colorindex = 5},
        {name = "Walcowana Stal", colorindex = 6},{name = "Cieniowe Srebro", colorindex = 7},
        {name = "Kamienne Srebro", colorindex = 8},{name = "Północne Srebro", colorindex = 9},
        {name = "Srebro Skąpane Żelazem", colorindex = 10},{name = "Czerwień", colorindex = 27},
        {name = "Turyńska Czerwień", colorindex = 28},{name = "Wyścigowa Czerwień", colorindex = 29},
        {name = "Czerwień Lawy", colorindex = 150},{name = "Płomienna Czerwień", colorindex = 30},
        {name = "Wdziękowa Czerwień", colorindex = 31},{name = "Granatowa Czerwień", colorindex = 32},
        {name = "Czerwień Zachodu Słońca", colorindex = 33},{name = "Czerwień Cabernet", colorindex = 34},
        {name = "Winna Czerwień", colorindex = 143},{name = "Cukierkowa Czerwień", colorindex = 35},
        {name = "Gorący Róż", colorindex = 135},{name = "Róż Pfsiter", colorindex = 137},
        {name = "Łososiowy Róż", colorindex = 136},{name = "Pomarańcz Wschodu Słońca", colorindex = 36},
        {name = "Pomorańcz", colorindex = 38},{name = "Jasna Pomarańcz", colorindex = 138},
        {name = "Złoto", colorindex = 99},{name = "Brąz", colorindex = 90},
        {name = "Żółć", colorindex = 88},{name = "Wyścigowa Żółć", colorindex = 89},
        {name = "Fluorescencyjna Żółć", colorindex = 91},{name = "Ciemna Zieleń", colorindex = 49},
        {name = "Wyścigowa Zieleń", colorindex = 50},{name = "Morska Zieleń", colorindex = 51},
        {name = "Oliwkowa Zieleń", colorindex = 52},{name = "Jasna Zieleń", colorindex = 53},
        {name = "Benzynowa Zieleń", colorindex = 54},{name = "Limonkowa Zieleń", colorindex = 92},
        {name = "Granatowy", colorindex = 141},
        {name = "Galaktyczny Niebieski", colorindex = 61},{name = "Ciemny Niebieski", colorindex = 62},
        {name = "Niebieski Saxon", colorindex = 63},{name = "Niebieski", colorindex = 64},
        {name = "Marynarski Błękit", colorindex = 65},{name = "Portowy Błękit", colorindex = 66},
        {name = "Brylantowy Błękit", colorindex = 67},{name = "Błękit Oceanu", colorindex = 68},
        {name = "Morski Błękit", colorindex = 69},{name = "Wyścigowy Błękit", colorindex = 73},
        {name = "Ultra Błękit", colorindex = 70},{name = "Jasny Niebieski", colorindex = 74},
        {name = "Czekoladową Brąz", colorindex = 96},{name = "Ciemny Brąz", colorindex = 101},
        {name = "Brąz Creëren", colorindex = 95},{name = "Brąz Feltzer", colorindex = 94},
        {name = "Klonowy Brąz", colorindex = 97},{name = "Bukowy Brąz", colorindex = 103},
        {name = "Surowy Brąz", colorindex = 104},{name = "Skórzany Brąz", colorindex = 98},
        {name = "Omszony Brąz", colorindex = 100},{name = "Sękowy Brąz", colorindex = 102},
        {name = "Słomiana Brąz", colorindex = 99},{name = "Piaskowy Brąz", colorindex = 105},
        {name = "Bielony Brąz", colorindex = 106},{name = "Fiolet Schaftera", colorindex = 71},
        {name = "Fiolet Spinnaker", colorindex = 72},{name = "Nocny Fiolet", colorindex = 142},
        {name = "Jasny Fiolet", colorindex = 145},{name = "Kremowy", colorindex = 107},
        {name = "Lodowa Biel", colorindex = 111},{name = "Mroźna Biel", colorindex = 112}
	},
	-- koła
	['frontWheel'] = {
		{name = "Fabryczne", wtype = 6, mod = -1, price = 0.4 * 1000},
		{name = "Speedway", wtype = 6, mod = 0, price = 0.4 * 1000},
		{name = "Streetspecial", wtype = 6, mod = 1, price = 0.4 * 1000},
		{name = "Racer", wtype = 6, mod = 2, price = 0.4 * 1000},
		{name = "Trackstar", wtype = 6, mod = 3, price = 0.4 * 1000},
		{name = "Overlord", wtype = 6, mod = 4, price = 0.4 * 1000},
		{name = "Trident", wtype = 6, mod = 5, price = 0.4 * 1000},
		{name = "Triplethreat", wtype = 6, mod = 6, price = 0.4 * 1000},
		{name = "Stilleto", wtype = 6, mod = 7, price = 0.4 * 1000},
		{name = "Wires", wtype = 6, mod = 8, price = 0.4 * 1000},
		{name = "Bobber", wtype = 6, mod = 9, price = 0.4 * 1000},
		{name = "Solidus", wtype = 6, mod = 10, price = 0.4 * 1000},
		{name = "Iceshield", wtype = 6, mod = 11, price = 0.4 * 1000},
		{name = "Loops", wtype = 6, mod = 12, price = 0.4 * 1000},
	},
	['backWheel'] = {
		{name = "Fabryczne", wtype = 6, mod = -1, price = 0.4 * 1000},
		{name = "Speedway", wtype = 6, mod = 0, price = 0.4 * 1000},
		{name = "Streetspecial", wtype = 6, mod = 1, price = 0.4 * 1000},
		{name = "Racer", wtype = 6, mod = 2, price = 0.4 * 1000},
		{name = "Trackstar", wtype = 6, mod = 3, price = 0.4 * 1000},
		{name = "Overlord", wtype = 6, mod = 4, price = 0.4 * 1000},
		{name = "Trident", wtype = 6, mod = 5, price = 0.4 * 1000},
		{name = "Triplethreat", wtype = 6, mod = 6, price = 0.4 * 1000},
		{name = "Stilleto", wtype = 6, mod = 7, price = 0.4 * 1000},
		{name = "Wires", wtype = 6, mod = 8, price = 0.4 * 1000},
		{name = "Bobber", wtype = 6, mod = 9, price = 0.4 * 1000},
		{name = "Solidus", wtype = 6, mod = 10, price = 0.4 * 1000},
		{name = "Iceshield", wtype = 6, mod = 11, price = 0.4 * 1000},
		{name = "Loops", wtype = 6, mod = 12, price = 0.4 * 1000},
	},
	['sportWheel'] = {
		{name = "Fabryczne", wtype = 0, mod = -1, price = 0.4 * 1000},
		{name = "Inferno", wtype = 0, mod = 0, price = 0.4 * 1000},
		{name = "Deepfive", wtype = 0, mod = 1, price = 0.4 * 1000},
		{name = "Lozspeed", wtype = 0, mod = 2, price = 0.4 * 1000},
		{name = "Diamondcut", wtype = 0, mod = 3, price = 0.4 * 1000},
		{name = "Chrono", wtype = 0, mod = 4, price = 0.4 * 1000},
		{name = "Feroccirr", wtype = 0, mod = 5, price = 0.4 * 1000},
		{name = "Fiftynine", wtype = 0, mod = 6, price = 0.4 * 1000},
		{name = "Mercie", wtype = 0, mod = 7, price = 0.4 * 1000},
		{name = "Syntheticz", wtype = 0, mod = 8, price = 0.4 * 1000},
		{name = "Organictyped", wtype = 0, mod = 9, price = 0.4 * 1000},
		{name = "Endov1", wtype = 0, mod = 10, price = 0.4 * 1000},
		{name = "Duper7", wtype = 0, mod = 11, price = 0.4 * 1000},
		{name = "Uzer", wtype = 0, mod = 12, price = 0.4 * 1000},
		{name = "Groundride", wtype = 0, mod = 13, price = 0.4 * 1000},
		{name = "Spacer", wtype = 0, mod = 14, price = 0.4 * 1000},
		{name = "Venum", wtype = 0, mod = 15, price = 0.4 * 1000},
		{name = "Cosmo", wtype = 0, mod = 16, price = 0.4 * 1000},
		{name = "Dashvip", wtype = 0, mod = 17, price = 0.4 * 1000},
		{name = "Icekid", wtype = 0, mod = 18, price = 0.4 * 1000},
		{name = "Ruffeld", wtype = 0, mod = 19, price = 0.4 * 1000},
		{name = "Wangenmaster", wtype = 0, mod = 20, price = 0.4 * 1000},
		{name = "Superfive", wtype = 0, mod = 21, price = 0.4 * 1000},
		{name = "Endov2", wtype = 0, mod = 22, price = 0.4 * 1000},
		{name = "Slitsix", wtype = 0, mod = 23, price = 0.4 * 1000},
	}, .----------------.  .----------------.  .----------------.  .----------------.   .----------------.  .----------------.  .----------------.  .----------------.  .----------------.   .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.   
	| .--------------. || .--------------. || .--------------. || .--------------. | | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. | | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |  
	| |    _______   | || |  _________   | || |      __      | || |  _______     | | | |   _____      | || |  _________   | || |      __      | || |  ___  ____   | || |    _______   | | | |  ____  ____  | || |  _________   | || |  _________   | || |   ______     | || |    _______   | || |  ________    | || |     _____    | || |    _______   | || |     ______   | || |     ____     | || |  _______     | || |  ________    | || |              | || |    ______    | || |    ______    | || |  ____  ____  | || | _____  _____ | || |     ______   | || |  ____  ____  | || |     _____    | || |  ____  ____  | || |   _    _     | || |  _________   | || |   ______     | || |     ____     | |  
	| |   /  ___  |  | || | |  _   _  |  | || |     /  \     | || | |_   __ \    | | | |  |_   _|     | || | |_   ___  |  | || |     /  \     | || | |_  ||_  _|  | || |   /  ___  |  | | | | |_   ||   _| | || | |  _   _  |  | || | |  _   _  |  | || |  |_   __ \   | || |   /  ___  |  | || | |_   ___ `.  | || |    |_   _|   | || |   /  ___  |  | || |   .' ___  |  | || |   .'    `.   | || | |_   __ \    | || | |_   ___ `.  | || |              | || |  .' ___  |   | || |  .' ___  |   | || | |_   ||   _| | || ||_   _||_   _|| || |   .' ___  |  | || | |_   ||   _| | || |    |_   _|   | || | |_  _||_  _| | || |  | |  | |    | || | |  _   _  |  | || |  |_   _ \    | || |   .' __ '.   | |  
	| |  |  (__ \_|  | || | |_/ | | \_|  | || |    / /\ \    | || |   | |__) |   | | | |    | |       | || |   | |_  \_|  | || |    / /\ \    | || |   | |_/ /    | || |  |  (__ \_|  | | | |   | |__| |   | || | |_/ | | \_|  | || | |_/ | | \_|  | || |    | |__) |  | || |  |  (__ \_|  | || |   | |   `. \ | || |      | |     | || |  |  (__ \_|  | || |  / .'   \_|  | || |  /  .--.  \  | || |   | |__) |   | || |   | |   `. \ | || |              | || | / .'   \_|   | || | / .'   \_|   | || |   | |__| |   | || |  | | /\ | |  | || |  / .'   \_|  | || |   | |__| |   | || |      | |     | || |   \ \  / /   | || |  | |__| |_   | || | |_/ | | \_|  | || |    | |_) |   | || |   | (__) |   | |  
	| |   '.___`-.   | || |     | |      | || |   / ____ \   | || |   |  __ /    | | | |    | |   _   | || |   |  _|  _   | || |   / ____ \   | || |   |  __'.    | || |   '.___`-.   | | | |   |  __  |   | || |     | |      | || |     | |      | || |    |  ___/   | || |   '.___`-.   | || |   | |    | | | || |      | |     | || |   '.___`-.   | || |  | |         | || |  | |    | |  | || |   |  __ /    | || |   | |    | | | || |              | || | | |    ____  | || | | |    ____  | || |   |  __  |   | || |  | |/  \| |  | || |  | |         | || |   |  __  |   | || |   _  | |     | || |    > `' <    | || |  |____   _|  | || |     | |      | || |    |  __'.   | || |   .`____'.   | |  
	| |  |`\____) |  | || |    _| |_     | || | _/ /    \ \_ | || |  _| |  \ \_  | | | |   _| |__/ |  | || |  _| |___/ |  | || | _/ /    \ \_ | || |  _| |  \ \_  | || |  |`\____) |  | | | |  _| |  | |_  | || |    _| |_     | || |    _| |_     | || |   _| |_      | || |  |`\____) |  | || |  _| |___.' / | || |     _| |_    | || |  |`\____) |  | || |  \ `.___.'\  | || |  \  `--'  /  | || |  _| |  \ \_  | || |  _| |___.' / | || |      _       | || | \ `.___]  _| | || | \ `.___]  _| | || |  _| |  | |_  | || |  |   /\   |  | || |  \ `.___.'\  | || |  _| |  | |_  | || |  | |_' |     | || |  _/ /'`\ \_  | || |      _| |_   | || |    _| |_     | || |   _| |__) |  | || |  | (____) |  | |  
	| |  |_______.'  | || |   |_____|    | || ||____|  |____|| || | |____| |___| | | | |  |________|  | || | |_________|  | || ||____|  |____|| || | |____||____| | || |  |_______.'  | | | | |____||____| | || |   |_____|    | || |   |_____|    | || |  |_____|     | || |  |_______.'  | || | |________.'  | || |    |_____|   | || |  |_______.'  | || |   `._____.'  | || |   `.____.'   | || | |____| |___| | || | |________.'  | || |     (_)      | || |  `._____.'   | || |  `._____.'   | || | |____||____| | || |  |__/  \__|  | || |   `._____.'  | || | |____||____| | || |  `.___.'     | || | |____||____| | || |     |_____|  | || |   |_____|    | || |  |_______/   | || |  `.______.'  | |  
	| |              | || |              | || |              | || |              | | | |              | || |              | || |              | || |              | || |              | | | |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |  
	| '--------------' || '--------------' || '--------------' || '--------------' | | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' | | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |  
	 '----------------'  '----------------'  '----------------'  '----------------'   '----------------'  '----------------'  '----------------'  '----------------'  '----------------'   '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'   
	['suvWheel'] = {
		{name = "Fabryczne", wtype = 3, mod = -1, price = 0.4 * 1000},
		{name = "Vip", wtype = 3, mod = 0, price = 0.4 * 1000},
		{name = "Benefactor", wtype = 3, mod = 1, price = 0.4 * 1000},
		{name = "Cosmo", wtype = 3, mod = 2, price = 0.4 * 1000},
		{name = "Bippu", wtype = 3, mod = 3, price = 0.4 * 1000},
		{name = "Royalsix", wtype = 3, mod = 4, price = 0.4 * 1000},
		{name = "Fagorme", wtype = 3, mod = 5, price = 0.4 * 1000},
		{name = "Deluxe", wtype = 3, mod = 6, price = 0.4 * 1000},
		{name = "Icedout", wtype = 3, mod = 7, price = 0.4 * 1000},
		{name = "Cognscenti", wtype = 3, mod = 8, price = 0.4 * 1000},
		{name = "Lozspeedten", wtype = 3, mod = 9, price = 0.4 * 1000},
		{name = "Supernova", wtype = 3, mod = 10, price = 0.4 * 1000},
		{name = "Obeyrs", wtype = 3, mod = 11, price = 0.4 * 1000},
		{name = "Lozspeedballer", wtype = 3, mod = 12, price = 0.4 * 1000},
		{name = "Extra vaganzo", wtype = 3, mod = 13, price = 0.4 * 1000},
		{name = "Splitsix", wtype = 3, mod = 14, price = 0.4 * 1000},
		{name = "Empowered", wtype = 3, mod = 15, price = 0.4 * 1000},
		{name = "Sunrise", wtype = 3, mod = 16, price = 0.4 * 1000},
		{name = "Dashvip", wtype = 3, mod = 17, price = 0.4 * 1000},
		{name = "Cutter", wtype = 3, mod = 18, price = 0.4 * 1000},
	},
	['offroadWheel'] = {
		{name = "Fabryczne", wtype = 4, mod = -1, price = 0.4 * 1000},
		{name = "Raider", wtype = 4, mod = 0, price = 0.4 * 1000},
		{name = "Mudslinger", wtype = 4, modtype = 23, wtype = 4, mod = 1, price = 0.4 * 1000},
		{name = "Nevis", wtype = 4, mod = 2, price = 0.4 * 1000},
		{name = "Cairngorm", wtype = 4, mod = 3, price = 0.4 * 1000},
		{name = "Amazon", wtype = 4, mod = 4, price = 0.4 * 1000},
		{name = "Challenger", wtype = 4, mod = 5, price = 0.4 * 1000},
		{name = "Dunebasher", wtype = 4, mod = 6, price = 0.4 * 1000},
		{name = "Fivestar", wtype = 4, mod = 7, price = 0.4 * 1000},
		{name = "Rockcrawler", wtype = 4, mod = 8, price = 0.4 * 1000},
		{name = "Milspecsteelie", wtype = 4, mod = 9, price = 0.4 * 1000},
	},
	['tunerWheel'] = {
		{name = "Fabryczne", wtype = 5, mod = -1, price = 0.4 * 1000},
		{name = "Cosmo", wtype = 5, mod = 0, price = 0.4 * 1000},
		{name = "Supermesh", wtype = 5, mod = 1, price = 0.4 * 1000},
		{name = "Outsider", wtype = 5, mod = 2, price = 0.4 * 1000},
		{name = "Rollas", wtype = 5, mod = 3, price = 0.4 * 1000},
		{name = "Driffmeister", wtype = 5, mod = 4, price = 0.4 * 1000},
		{name = "Slicer", wtype = 5, mod = 5, price = 0.4 * 1000},
		{name = "Elquatro", wtype = 5, mod = 6, price = 0.4 * 1000},
		{name = "Dubbed", wtype = 5, mod = 7, price = 0.4 * 1000},
		{name = "Fivestar", wtype = 5, mod = 8, price = 0.4 * 1000},
		{name = "Slideways", wtype = 5, mod = 9, price = 0.4 * 1000},
		{name = "Apex", wtype = 5, mod = 10, price = 0.4 * 1000},
		{name = "Stancedeg", wtype = 5, mod = 11, price = 0.4 * 1000},
		{name = "Countersteer", wtype = 5, mod = 12, price = 0.4 * 1000},
		{name = "Endov1", wtype = 5, mod = 13, price = 0.4 * 1000},
		{name = "Endov2dish", wtype = 5, mod = 14, price = 0.4 * 1000},
		{name = "Guppez", wtype = 5, mod = 15, price = 0.4 * 1000},
		{name = "Chokadori", wtype = 5, mod = 16, price = 0.4 * 1000},
		{name = "Chicane", wtype = 5, mod = 17, price = 0.4 * 1000},
		{name = "Saisoku", wtype = 5, mod = 18, price = 0.4 * 1000},
		{name = "Dishedeight", wtype = 5, mod = 19, price = 0.4 * 1000},
		{name = "Fujiwara", wtype = 5, mod = 20, price = 0.4 * 1000},
		{name = "Zokusha", wtype = 5, mod = 21, price = 0.4 * 1000},
		{name = "Battlevill", wtype = 5, mod = 22, price = 0.4 * 1000},
		{name = "Rallymaster", wtype = 5, mod = 23, price = 0.4 * 1000},
	},
	['highWheel'] = {
		{name = "Fabryczne", wtype = 7, mod = -1, price = 0.4 * 1000},
		{name = "Shadow", wtype = 7, mod = 0, price = 0.4 * 1000},
		{name = "Hyper", wtype = 7, mod = 1, price = 0.4 * 1000},
		{name = "Blade", wtype = 7, mod = 2, price = 0.4 * 1000},
		{name = "Diamond", wtype = 7, mod = 3, price = 0.4 * 1000},
		{name = "Supagee", wtype = 7, mod = 4, price = 0.4 * 1000},
		{name = "Chromaticz", wtype = 7, mod = 5, price = 0.4 * 1000},
		{name = "Merciechlip", wtype = 7, mod = 6, price = 0.4 * 1000},
		{name = "Obeyrs", wtype = 7, mod = 7, price = 0.4 * 1000},
		{name = "Gtchrome", wtype = 7, mod = 8, price = 0.4 * 1000},
		{name = "Cheetahr", wtype = 7, mod = 9, price = 0.4 * 1000},
		{name = "Solar", wtype = 7, mod = 10, price = 0.4 * 1000},
		{name = "Splitten", wtype = 7, mod = 11, price = 0.4 * 1000},
		{name = "Dashvip", wtype = 7, mod = 12, price = 0.4 * 1000},
		{name = "Lozspeedten", wtype = 7, mod = 13, price = 0.4 * 1000},
		{name = "Carboninferno", wtype = 7, mod = 14, price = 0.4 * 1000},
		{name = "Carbonshadow", wtype = 7, mod = 15, price = 0.4 * 1000},
		{name = "Carbonz", wtype = 7, mod = 16, price = 0.4 * 1000},
		{name = "Carbonsolar", wtype = 7, mod = 17, price = 0.4 * 1000},
		{name = "Carboncheetahr", wtype = 7, mod = 18, price = 0.4 * 1000},
		{name = "Carbonsracer", wtype = 7, mod = 19, price = 0.4 * 1000},
	},
	['lowriderWheel'] = {
		{name = "Fabryczne", wtype = 2, mod = -1, price = 0.4 * 1000},
		{name = "Flare", wtype = 2, mod = 0, price = 0.4 * 1000},
		{name = "Wired", wtype = 2, mod = 1, price = 0.4 * 1000},
		{name = "Triplegolds", wtype = 2, mod = 2, price = 0.4 * 1000},
		{name = "Bigworm", wtype = 2, mod = 3, price = 0.4 * 1000},
		{name = "Sevenfives", wtype = 2, mod = 4, price = 0.4 * 1000},
		{name = "Splitsix", wtype = 2, mod = 5, price = 0.4 * 1000},
		{name = "Freshmesh", wtype = 2, mod = 6, price = 0.4 * 1000},
		{name = "Leadsled", wtype = 2, mod = 7, price = 0.4 * 1000},
		{name = "Turbine", wtype = 2, mod = 8, price = 0.4 * 1000},
		{name = "Superfin", wtype = 2, mod = 9, price = 0.4 * 1000},
		{name = "Classicrod", wtype = 2, mod = 10, price = 0.4 * 1000},
		{name = "Dollar", wtype = 2, mod = 11, price = 0.4 * 1000},
		{name = "Dukes", wtype = 2, mod = 12, price = 0.4 * 1000},
		{name = "Lowfive", wtype = 2, mod = 13, price = 0.4 * 1000},
		{name = "Gooch", wtype = 2, mod = 14, price = 0.4 * 1000},
	},
	['muscleWheel'] = {
		{name = "Fabryczne", wtype = 1, mod = -1, price = 0.4 * 1000},
		{name = "Classicfive", wtype = 1, mod = 0, price = 0.4 * 1000},
		{name = "Dukes", wtype = 1, mod = 1, price = 0.4 * 1000},
		{name = "Musclefreak", wtype = 1, mod = 2, price = 0.4 * 1000},
		{name = "Kracka", wtype = 1, mod = 3, price = 0.4 * 1000},
		{name = "Azrea", wtype = 1, mod = 4, price = 0.4 * 1000},
		{name = "Mecha", wtype = 1, mod = 5, price = 0.4 * 1000},
		{name = "Blacktop", wtype = 1, mod = 6, price = 0.4 * 1000},
		{name = "Dragspl", wtype = 1, mod = 7, price = 0.4 * 1000},
		{name = "Revolver", wtype = 1, mod = 8, price = 0.4 * 1000},
		{name = "Classicrod", wtype = 1, mod = 9, price = 0.4 * 1000},
		{name = "Spooner", wtype = 1, mod = 10, price = 0.4 * 1000},
		{name = "Fivestar", wtype = 1, mod = 11, price = 0.4 * 1000},
		{name = "Oldschool", wtype = 1, mod = 12, price = 0.4 * 1000},
		{name = "Eljefe", wtype = 1, mod = 13, price = 0.4 * 1000},
		{name = "Dodman", wtype = 1, mod = 14, price = 0.4 * 1000},
		{name = "Sixgun", wtype = 1, mod = 15, price = 0.4 * 1000},
		{name = "Mercenary", wtype = 1, mod = 16, price = 0.4 * 1000},
	},
}
--[[ _____ _               _                _          _     _   _                 _ _                       _              _     _    _      _   _    _____   __  ___ _   _     _____  
/  ___| |             | |              | |        | |   | | | |               | (_)                     | |            | |   | |  | |    | | | |  |_  \ \ / / /   | | | |   |  _  | 
\ `--.| |_ __ _ _ __  | |     ___  __ _| | _____  | |__ | |_| |_ _ __  ___  __| |_ ___  ___ ___  _ __ __| |  __ _  __ _| |__ | |  | | ___| |_| |    | |\ V / / /| | |_| |__  \ V /  
 `--. \ __/ _` | '__| | |    / _ \/ _` | |/ / __| | '_ \| __| __| '_ \/ __|/ _` | / __|/ __/ _ \| '__/ _` | / _` |/ _` | '_ \| |/\| |/ __|  _  |    | |/   \/ /_| | __| '_ \ / _ \  
/\__/ / || (_| | |    | |___|  __/ (_| |   <\__ \ | | | | |_| |_| |_) \__ \ (_| | \__ \ (_| (_) | | | (_| || (_| | (_| | | | \  /\  / (__| | | |/\__/ / /^\ \___  | |_| |_) | |_| | 
\____/ \__\__,_|_|    \_____/\___|\__,_|_|\_\___/ |_| |_|\__|\__| .__/|___/\__,_|_|___/\___\___/|_|  \__,_(_)__, |\__, |_| |_|\/  \/ \___\_| |_/\____/\/   \/   |_/\__|_.__/\_____/ 
                                                                | |                                          __/ | __/ |                                                            
                                                                |_|                                         |___/ |___/                                                             
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                    ]]