Config = {
    ["UsingLoader"]     = false,
    
    ["UsingESX"]        = true,
    ["UsingESX_V1.2.0"] = false,
    ["UsingKashacters"] = false,
    ["CashAccountName"] = "money",
    ["BankAccountName"] = "bank",
}

Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Couches"] = {
    [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Стар диван на цветя" },
    [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "Тройна пейка" },
    [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Стар фотьойл 1" },
    [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Стар троен диван" },
    [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Стар двоен диван" },
    [6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Малък фотьойл" },
    [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["name"] = "Ъглов диван за хол 1" },
    [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["name"] = "Ъглов диван за хол 2" },
    [9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Диван 1" },
    [10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Диван 2" },
    [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Фотьойл" },
    [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "Дървен Диван" },
    [13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Диван 3" },
    [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Двоен диван " },
    [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Счупен диван" },
    [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Диван 4" },
    [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Диван 5" },
    [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Диван 6" },
    [19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Холна пейка" },
    [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "Табуретка с поднос 1" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "Табуретка с поднос 2" },
  },

  ["Chairs"] = {
    [1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "Бар стол 1" },
    [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Стол 1" },
    [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Стол 2" },
    [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "Кухненска пейка" },
    [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Кухненски стол 1" },
    [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Кухненски стол 2" },
    [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Кухненски стол 3" },
    [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Кухненска пейка 2" },
    [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Бар стол 2" },
    [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "Голям Фотьойл" },
    [11] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Малкък Фотьойл" },
    [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Кухненски стол с колела" },
    [13] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Табуретка" },
    [14] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "Бял Стол" },
    [15] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Бял фотьойл" },
    [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Кухненски стол 4" },
    [17] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Кухненски стол 5" },
    [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Градински стол 1" },
    [19] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Дървен бял стол" },
    [20] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Офис стол" },
    [21] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Бар стол 3" },
    [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Бар стол 4" },
    [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Бар стол 5" },
    [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Стол Офис" },
    [25] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Бял холов стол" },
    [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Бял текстилен Фотьойл" },
    [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Директоркси стол 1" },
    [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Директорски стол 2" },
    [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Градински мебели 1" },
    [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Градински мебели 2" },
    [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Градински мебели 3" },
    [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Градински мебели 4" },
    [33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "Дървен стол 1" },
    [34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Дурвен стол 2" },
    [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "Въртящ стол" },
    [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Офис стол" },
  },

  ["Beds"] = {
    [1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "Ретро легло" },  
    [2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "Дървено легло" }, 
    [3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "Дървено легло лукс" }, 
    [4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "Дървено легло лукс" }, 
    [5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Кожено легло" },  
    [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "Легло 1" }, 
    [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "Легло 2" }, 
    [8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "Текстилно легло" },
    [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 700, ["name"] = "Двойно легло" },  
    [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 700, ["name"] = "Двойно легло 2" },
    [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 700, ["name"] = "Тройно легло 3" },
    [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "Спалня с шкафчета" },
    [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 500, ["name"] = "Единично легло" },
  },

  ["General #1"] = {
    [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Барбарон" },
    [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "Бяла ваза" },
    [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Кожена стена" },
    [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Глава от козел" },
    [5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Кухненски прибори" },
    [6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Книга за рецепти" },
    [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Отворена книга за рецепти" },
    [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Поставка за книги" },
    [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Фитнес пътека" },
    [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Пътека за Йога" },
    [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Кутия за парфюми" },
    [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Ваза с цвете" },
    [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Купа с плодове" },
    [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Кошница за пране" },
    [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "Табуретка" },
    [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Скулптура" },
    [17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Поставка за списания" },
    [18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Кутия за бижута" },
    [19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Кошче" },
    [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Фруктиера" },
    [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Бронзова ваза" },
    [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Дъска с тебешири" },
    [23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Скрин с огледало" },
    [24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Мраморна стойка" },
    [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Пепелник" },
    [26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Малък свещник" },
    [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Голям свещник" },
    [28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Кухненска везна" },
    [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Възглавница" },
    [30] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 300, ["name"] = "Картина 1" },
    [31] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 300, ["name"] = "Картина 2" },
    [32] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Катина 3" },
    [33] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 300, ["name"] = "Картина 4" },
    [34] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 300, ["name"] = "Картина 5" },
    [35] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 300, ["name"] = "Килим 1" },
    [36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 300, ["name"] = "Килим 2" },
    [37] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 300, ["name"] = "Килим 3" },
    [38] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 100, ["name"] = "Скрин"}
  },

  ["General #2"] = {
    [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "A4 Лист" },
    [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "Голяма бира" },
    [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Малка бира" },
    [4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Очила" },
    [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Тетрадки" },
    [6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Кашон с бира" },
    [7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Бинокъл" },
    [8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Препарат за прозорци" },
    [9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Барабани" },
    [10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Бонг" },
    [11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Касетофон" },
    [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Купа с чипс" },
    [13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Кутия с бонбони" },
    [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Пазарна чанта" },
    [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Керамична кана" },
    [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Кутия с цигари 1" },
    [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Кутия с цигари 2" },
    [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Кашон с бира отворен 2" },
    [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Папка" },
    [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Чаша със сламка" },
    [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Пощенски плик" },
    [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Чаша за шампанско" },
    [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Малък сак" },
    [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "Диск" },
    [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "Кутия за диск" },
    [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Филмова лента" },
    [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Вертикални щори" },
    [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Пакет" },
    [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Дъска за гладене" },
    [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Катана" },
    [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Кана за вода" },
    [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Щайга" },
    [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Туба за гориво" },
    [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Чувал" },
    [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Бутилка" },
    [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Шише" },
    [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Чувал с боклук" },
    [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Бутилка с уиски" },
    [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Червен бонг" },
    [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Паница с фъстъци" },
    [41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Чаша с уиски" },
  },

  ["General #3"] = {
    [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "Пълно кошче" },
    [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Плетен кош" },
    [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "Сак 1" },
    [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "Сак 2" },
    [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "Мрежесто кошче" },
    [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Касов апарат" },
    [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "Висок стол" },
    [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "Пластмасов стол" },
    [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Стенен часовник" },
    [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Крем 1" },
    [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Крем 2" },
    [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Крем 3" },
    [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Крем 4" },
    [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Крем 5" },
    [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Крем 6" },
    [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "Работен шкаф 1" },
    [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "Работна маса" },
    [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Стар хладилник" },
    [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Куфар 1" },
    [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Куфар 2" },
    [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Книга 1" },
    [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Книга 2" },
    [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Книга 3" },
    [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Книга 4" },
    [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Шотоапарат" },
    [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "Аптечка" },
    [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Фигура" },
    [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Списания 1" },
    [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Списания 2" },
    [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Череп" },
    [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Китара" },
    [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Дамска чанта" },
    [33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Отворен куфар" },
    [34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Голям сак" },
    [35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Нож от кокъл " },
    [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Варел с химикали" },
    [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Хартиена чанта" },
    [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Отварачка" },
    [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Парцалена кукла" }, 
  },

  ["General #4"] = {
    [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Пластмасов манекен" },
    [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Стенен часовник" },
    [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "Електрическа китара 1" },
    [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "Електрическа китара 2" },
    [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "Електрическа китара 3" },
    [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Чувал с фураж" },
    [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Моп" },
    [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Плетена кошница" },
    [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Голям моп" },
    [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Подложка" },
    [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Голям часовник" },
    [12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Дървена кутия" },
    [13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Часовник" },
    [14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Часовник 1" },
    [15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Часовник 2" },
    [16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Часовник 3" },
    [17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Часовник 4" },
    [18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Часовник 5" },
    [19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Часовник 6" },
    [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Бижута" },
    [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Бижута 1" },
    [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Бижута 2" },
    [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Бижута 3" },
    [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Бижута 4" },
    [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Бижута 5" },
    [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Бижута 6" },
    [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Бижута 7" },
    [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Зелена сцена" },
    [29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Дамска чанта" },
    [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Бутилка с гориво" },
    [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Безжична аларма с клавиатура" },
    [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Безжична аларма с клавиатура 2" },
    [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Куфар 1" },
    [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Куфар 2" },
    [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Куфар 3"},
    [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Мечето ТЕД" },
    [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Хартиена чанта" },
    [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Хартиени чанти" },
    [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Чанти за пазар" },
    [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Пътека 1" },
    [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Пътека 2" },
    [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Пътека 3" },
    [43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Саксофон" },
    [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "Футболна топка" },
    [45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Ръчен часовник 1" },
    [46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Ръчен часовник 2" },
    [47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Ръчен часовник 3" },
    [48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Ръчен часовник 4" },
    [49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Ръчен часовник 5" },
    [51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Ръчен часовник 6" },
  },

  ["Small"] = {
    [1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Фигура котка" },
    [2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Фигура клоун" },
    [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Картина" },
    [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Фигура жена" },
    [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Фигура фламинго" },
    [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Фигура момиче" },
    [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Фигура момиче" },
    [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Фигура" },
    [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Фигура" },
    [10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Чайник" },
    [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Фигура 1" },
    [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Дървено слонче 2" },
    [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Дървени слончета 3" },
    [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Фигура пума 4" },
    [15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Скейтборд" },
    [16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Тетрадки" },
    [17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Носни кърпи кутия" },
    [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Плетен панер" },
    [19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Кошче" },
    [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Възглавница 1" },
    [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Възглавница 2" },
    [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Възглавница 3" },
    [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Възглавница 4" },
    [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Възглавница 5" },
    [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Възглавница 6" },
    [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Декорация за маса" },
    [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Малък шкаф" },
    [28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Скулптура" },
    [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["name"] = "Белезници" },
    [30] = { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Дилдо" },
    [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Дилдо 2" },
    [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Дилдо 3" },
    [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "Дилдо 4" },
    [34] = { ["object"] = "v_res_d_lube", ["price"] = 100, ["name"] = "Лубрикант" },
    [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Документация" },
    [36] = { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "Кутия за документи" },
  },

  ["Storage"] = {
    [1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Секция за кабинет" },
    [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Тоалетка с огледало" },
    [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Шкаф" },
    [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Шкаф" },
    [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Шкаф" },
    [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Нощно шкафче" },
    [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Шкаф с телевизор" },
    [8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Шкаф" },
    [9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Луксозен шкаф" },
    [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Дървен шкаф" },
    [11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Дървен шкаф висок" },
    [12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Дървен шкаф с чекмеджета" },
    [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Голяма Секция с уредба" },
    [14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Дървен гардероб" },
    [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Тоалетка с огледало" },
    [16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Секция скрин" },
    [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Шкафче с чекмеджета 1" },
    [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Шкафче с чекмеджета 2" },
    [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Шкаф за книги" },
    [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Дървена ракла" },
    [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Дървен шкаф" },
    [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Гардероб" },
    [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Малка Секция" },
    [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Плетена ракла 1" },
    [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Голям пластмасов сандък 1" },
    [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Пластмасов сандък 2" },
    [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Сейф" },
  },

  ["Electronics"] = {
    [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Стар хладилник" },
    [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Тонколона за стена" },
    [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Bluetooth колонка" },
    [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Декоративен часовник" },
    [5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Домашен телефон" },
    [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Електрическа печка висока" },
    [7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Вентилатор" },
    [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Екран" },
    [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Монитор" },
    [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Кухненски робот" },
    [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "Камера" },
    [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Лаптоп" },
    [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Монитор" },
    [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "55 инчов телевизор TV" },
    [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "Смарт телевизор СЕТ" },
    [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "Телевизор СЕТ 1" },
    [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1000, ["name"] = "Телевизор СЕТ 2" },
    [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Грамофон голям" },
    [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Вентилатор на стойка" },
    [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "клавиатура" },
    [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Кафемашина" },
    [22] = { ["object"] = "prop_tv_flat_01", ["price"] = 500, ["name"] = "Телевизор с Нетфликс" },
  },


  ["Lighting"] = {
    [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Настолна лампа" },
    [2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Настолна лампа 2" },
    [3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Нощна лапма" },
    [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Нощна лампа 1" },
    [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Лампа" },
    [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Лампа 2" },
    [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Нощна лампа" },
    [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Нощна лампа 2" },
    [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Нощна лампа розова" },
    [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Саксия с цвете" },
    [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Лампа" },
    [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Висока лампа" },
    [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Висока лампа 2" },
    [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Висока лампа 3" },
    [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Лампа с вентилатор" },
    [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Лампа" },
    [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Лампа свещи" },
    [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "Лампа" },
    [19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Светещи диоди" },
    [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Лампа" },
    [21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Тест лампа" },
  },


  ["Tables"] = {
    [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Холна маса 1" },
    [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Холна маса 2" },
    [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Малка холна маса" },
    [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Железна маса" },
    [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Малка маса" },
    [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Стъклена маса" },
    [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Стъклена голяма маса" },
    [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Дървена малка маса" },
    [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Малка маса" },
    [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Нощно шкафче" },
    [11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Скрин" },
    [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Кръгла маса" },
    [13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Дървена голяма маса" },
    [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Кръгла голяма маса" },
    [15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Дървена маса" },
    [16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Малка масичка ниска" },
    [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Малък скрин" },
    [18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Дървена маса" },
    [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Маса за телевизор" },
    [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Маса за телевизор 2" },
    [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Стъклена холна маса" },
    [22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Дълго бюро" },
    [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Пластмасова малка масичка" },
    [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Средна ластмасова маса" },
    [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Голяма пластмасова маса" },
    [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "Кръгла маса" },
    [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 100, ["name"] = "Голяма бяла маса със столове" },
  },

  ["Plants"] = {
    [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Цветя" },
    [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Цветя 1" },    
    [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Цветя 2" }, 
    [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Китайско цвете" }, 
    [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Дърво банан" }, 
    [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Палми" },  
    [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Палми 1" },  
    [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Широколистно цвете" },  
    [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Цвете" }, 
    [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Цвете 1" }, 
    [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Цвете 2" }, 
    [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Цвете 3" }, 
    [13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Цветя 1" },
    [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Цветя 2" },
    [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Цветя 3" },
    [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 100, ["name"] = "Цветя 4" },
    [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Цветя 5" },
    [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Коледно дърво" },
  },

  ["Kitchen"] = {
    [1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Пералня 1" },
    [2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Пералня 2" },
    [3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Пералня 3" },
    [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Панер" },
    [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Хладилник 1" },
    [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Хладилник 2" },
    [7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Хладилник 3" },
    [8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Хладилник 4" },
    [9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Котлони с фурни" },
    [10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Микровълнова фурна 1" },
    [11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Микровълнова фурна 2" },
    [12] = { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Тиган" },
    [13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Поднос за торта с капак" },
    [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Дървена дъска" },
    [15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Шпатули и бъркалки" },
    [16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Мелачка за чесън" },
    [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "Кухненска хартия 1" },
    [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "Кухненска хартия 2" },
    [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Тенджера 1" },
    [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Тенджера 2" },
    [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Тенджера 3" },
    [22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Тенджера 4" },
    [23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Тенджера 5" },
    [24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Тенджера 6" },
    [25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Тенджера 7" },
    [26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Стойка с тигани и тенджери" },
    [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Сокоизтисквачки" },
  },


  ["Bathroom"] = {
    [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Мръсна тоалетна" },
    [2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Тоалетна 1" },
    [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Тоалетна 2" },
    [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Керамична мивка" },
    [5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Желязна мивка" },
    [6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Малка мивка" },
    [7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Висока мивка" },
    [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Диспенсър за сапун" },
    [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Етaжерка за баня" },
    [10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Сешоар за ръце" },
    [11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Сешоар за ръце 1" },
    [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Кърпи за баня 1" },
    [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Кърпи за баня 2" },
    [14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Кърпи 1" },
    [15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Кърпи 2" },
    [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Кърпи 3" },
    [17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Вана" },
    [18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Мивка" },
  },

  ["Medical"] = {
    [1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Варел" },
    [2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Клетка" },
    [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Голяма клетка" },
    [4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Болнично легло 1" },
    [5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Болнично легло 2" },
    [6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Скрин" },
    [7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Железен шкаф 1" },
    [8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Железен шкаф  2" },
    [9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Железен шкаф с мивка" },
    [10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Апаратура" },
    [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Маса за аутопсия" },
    [12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Кош" },
    [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Уреди за вземане на проби" },
    [14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Хладилник" },
    [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Монитор" },
    [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Маса за аутопсия 2" },
    [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Кош" },
    [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Маса с колела" },
    [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Туба" },
    [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "Маса за аутопсия 3" },
    [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "Кутия за документи" },
    [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "Шкаф за документи" },
    [23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Навит маркуч" },
    [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Голям железен шкаф" },
    [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Светещо табло" },
    [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Мед. стол" },
    [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Мини хладилник" },
    [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Хартия" },
    [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Принтер" },
    [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "Телевизор" },
    [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Шкаф с медикаменти" },
    [32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Лампа" },
    [33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Газова бутилка голяма" },
    [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Кантар" },
    [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Апаратура за стена" },
    [36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Кресла" },
    [37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Маса" },
    [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Медикаменти" },
    [39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Контейнер за опасни отпадъци" },
    [40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Апарат" },
    [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Аптечка" },
  },
  ["PC"] = {
    [1] = { ["object"] = "prop_laptop_jimmy", ["price"] = 1600, ["name"] = "Лаптоп" },
    [2] = { ["object"] = "prop_laptop_01a", ["price"] = 1600, ["name"] = "Лаптоп 1" },
    [3] = { ["object"] = "v_res_monitor", ["price"] = 750, ["name"] = "Монитор" },
    [4] = { ["object"] = "prop_monitor_01a", ["price"] = 750, ["name"] = "Монитор 2" },
    [5] = { ["object"] = "prop_monitor_04a", ["price"] = 750, ["name"] = "Монитор 3" },
    [6] = { ["object"] = "prop_monitor_li", ["price"] = 750, ["name"] = "Монитор 4" },
    [7] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 200, ["name"] = "Клавиатура" },
    [8] = { ["object"] = "prop_keyboard_01a", ["price"] = 200, ["name"] = "Клавиатура 1" },
    [9] = { ["object"] = "hei_prop_hei_cs_keyboard", ["price"] = 200, ["name"] = "Клавиатура 2" },
    [10] = { ["object"] = "prop_cs_mouse_01", ["price"] = 120, ["name"] = "Мишка" },
    [11] = { ["object"] = "prop_mouse_01a", ["price"] = 120, ["name"] = "Мишка 1" },
    [12] = { ["object"] = "v_res_mousemat", ["price"] = 140, ["name"] = "Мишка 2" },
    [13] = { ["object"] = "ba_prop_battle_headphones_dj", ["price"] = 320, ["name"] = "Телефон" },
    [14] = { ["object"] = "prop_podium_mic", ["price"] = 60, ["name"] = "Микрофон" },
    [15] = { ["object"] = "prop_table_mic_01", ["price"] = 60, ["name"] = "Микрофон 2" },
  }
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end

if not Config.UsingNativeHousing then
  TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
  Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]